name: CI
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "bin/*"
  push:
    paths:
      - "bin/*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'macos-latest'
        run: brew install icu4c
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: usql --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
